condense_wildcard_suffixes=true
format_code_in_doc_comments=true
group_imports="StdExternalCrate"
imports_granularity="Crate"
imports_layout="HorizontalVertical"
match_block_trailing_comma=true
merge_imports=true
normalize_comments=true
normalize_doc_attributes=true
reorder_impl_items=true
reorder_imports=true
reorder_modules=true
use_field_init_shorthand=true
use_try_shorthand=true
